<?php
/**
 * Vertical image callout.
 *
 * @package standard-industries
 */

use Rain\Modules;

$modules = Modules::get_instance();

$modules->add_module('Vertical Image Callout', 'grid-vertical-image-callout', 'page_modules',
	array(
		array(
			'key' => 'field_5994bdff9cfcf',
			'label' => 'First column size',
			'name' => 'first_column_size',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'small' => 'Small',
				'large' => 'Large',
			),
			'default_value' => array(),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5994bb8c9cfc4',
			'label' => 'Columns',
			'name' => 'columns',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 2,
			'layout' => 'block',
			'button_label' => 'Add Column',
			'sub_fields' => array(
				array(
					'key' => 'field_5994bba99cfc5',
					'label' => 'Column Type',
					'name' => 'column_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'default' => 'Default Image and Text',
						'wcta' => 'Image with CTA Button Links',
						'image' => 'Image',
						'text' => 'Text (optionally CTA Button Links)',
					),
					'default_value' => array(),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5994bbf19cfc6',
					'label' => 'Column Image',
					'name' => 'column_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5994bba99cfc5',
								'operator' => '!=',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5994bbfc9cfc7',
					'label' => 'Column Headline',
					'name' => 'column_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5994bba99cfc5',
								'operator' => '!=',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59adb4b1e2698',
					'label' => 'Headline Color',
					'name' => 'headline_color',
					'type' => 'clone',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5994bba99cfc5',
								'operator' => '!=',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'clone' => array(
						0 => 'field_599c98469795c',
					),
					'display' => 'seamless',
					'layout' => 'block',
					'prefix_label' => 0,
					'prefix_name' => 0,
				),
				array(
					'key' => 'field_5994bc0a9cfc8',
					'label' => 'Column Text',
					'name' => 'column_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5994bba99cfc5',
								'operator' => '!=',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_5995cf2fadc3f',
					'label' => 'CTA Button Links',
					'name' => 'cta_button_links',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5994bba99cfc5',
								'operator' => '==',
								'value' => 'wcta',
							),
						),
						array(
							array(
								'field' => 'field_5994bba99cfc5',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 2,
					'layout' => 'block',
					'button_label' => 'Add CTA Button Link',
					'sub_fields' => array(
						array(
							'key' => 'field_5995cf67adc40',
							'label' => 'CTA or Image?',
							'name' => 'cta_or_image',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'cta' => 'CTA Button Link',
								'image' => 'Image Placeholder',
							),
							'default_value' => array(),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'clone' => array(
								1 => 'group_component_button',
							),
							'prefix_label' => 0,
							'prefix_name' => 0,
							'display' => 'group',
							'layout' => 'block',
							'key' => 'field_5994b67549cf',
							'label' => 'CTA Button Link',
							'name' => 'cta_button_link',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5995cf67adc40',
										'operator' => '==',
										'value' => 'cta',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array(
							'key' => 'field_5994bcbd9cfcb',
							'label' => 'Small image after CTA',
							'name' => 'small_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5995cf67adc40',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_e6ede70028840',
							'label' => 'Background Image',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
			),
		),
	)
);
